#!/bin/sh -e

case "$1" in
  configure)
    # prefill hdf
    . /usr/share/yavdr/helpers/hdf_prefill

    hdf_prefill "system.remoted" "eventlircd"
    hdf_prefill "system.remote.lirc.active" "0"
    hdf_prefill "system.remote.lirc.receiver.serial_port" "/dev/ttyS0"
    hdf_prefill "system.remote.lirc.receiver.description" "Home-brew MCE profile (16x50 UART compatible serial port)"
    hdf_prefill "system.remote.lirc.receiver.driver" "serial"
    hdf_prefill "system.remote.lirc.receiver.lirc_driver" "lirc_dev lirc_serial"
    hdf_prefill "system.remote.lirc.receiver.hw_default" "hw_default"
    hdf_prefill "system.remote.lirc.receiver.lircd_conf" "lircd.conf"
    hdf_prefill "system.remote.lirc.option.repeat" "0"

    process-template /etc/init/lircd2uinput.conf
    process-template /etc/rc_maps.cfg
  ;;

esac

exit 0

